kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    channels:
    - name: stable-4.19
      minVersion: 4.19.10
      maxVersion: 4.19.10
    graph: true 
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.19
      packages: 
       - name: advanced-cluster-management
       - name: metallb-operator
       - name: lvms-operator
       - name: multicluster-engine
  additionalImages: 
   - name: registry.redhat.io/ubi8/ubi:latest
